<?php

/**
 * An Inputfieldtype for handling Colors
 * used by the FieldtypeColorPicker
 *
 * 08.08.2012 by Philipp "Soma" Urlich
 * ColorPicker jQuery Plugin by http://www.eyecon.ro/colorpicker/
 *
 */

class InputfieldColorPicker extends Inputfield {

	public static function getModuleInfo() {
		return array(
			'title' => 'ColorPicker',
			'version' => 101,
			'summary' => 'Chose your colors the easy way.',
			'href' => 'http://processwire.com/talk/topic/865-module-colorpicker/page__gopid__7340#entry7340',
			'requires' => array("FieldtypeColorPicker")
			);
	}

	public function __construct() {
		parent::__construct();
		$this->setAttribute('type', 'hidden');
	}


	public function init() {
		parent::init();
		$conf = $this->getModuleInfo();
		$version = (int) $conf['version'];
		$this->config->styles->add($this->config->urls->InputfieldColorPicker . "colorpicker/css/colorpicker.css?v={$version}");
		$this->config->scripts->add($this->config->urls->InputfieldColorPicker . "colorpicker/js/colorpicker.js?v={$version}");
	}


	public function ___render() {
		$out = "\n<p><div id='ColorPicker_$this->name' style='border:2px solid #444;display:block;width:40px;height:40px;background-color:#".$this->value."'></div>";
		$out .= "<input " . $this->getAttributesString() . " /></p>";
		$out .= <<<_OUT
<script type='text/javascript'>
	$('#ColorPicker_$this->name').ColorPicker({
		color: '#$this->value',
		onShow: function (colpkr) {
			$(colpkr).fadeIn(500);
			return false;
		},
		onHide: function (colpkr) {
			$(colpkr).fadeOut(500);
			return false;
		},
		onChange: function (hsb, hex, rgb) {
			$('#ColorPicker_$this->name').css('backgroundColor', '#' + hex);
			$('#Inputfield_$this->name').val(hex).trigger('change');
		}
	});

</script>

_OUT;

		return $out;
	}
}
